baseurl = "http://example.netlify.io/"
relativeurls = false
languageCode = "en-us"
title = "Bomi Lee"
theme = "hugo-prof"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
uglyURLS = false
enableEmoji = true
blogdir = "blog"

[permalinks]
    post = "blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
#[[menu.main]]           # comment out this row, plus the name, url, and weight to omit  
#   name = "Research"    
#   url = "/research/"
#   weight = 2
#[[menu.main]]           # comment out this row, plus the name, url, and weight to omit 
#   name = "Teaching"
#   url = "/teaching/"
#   weight = 3
#[[menu.main]]           # comment out this row, plus the name, url, and weight to omit 
#    name = "Blog"
#    url = "/blog/"
#    weight = 4
[[menu.main]]
    name = "CV"
    url = "/bomi-rmarkdown-cv.pdf"
    weight = 5

[params]
    description = "International Conflict, Interstate Rivalries, International Relations and Domestic Politics, Diversionary Theory" 
    subtitle = "International Conflict, Interstate Rivalries, International Relations and Domestic Politics, Diversionary Theory."
    home_text = "Greetings! I am a Ph.D student of political science at the University of Iowa. I received my B.A. in political science and M.A. in international relations from Seoul National University. My research and teaching interests include international conflict, international rivalries, and diversionary theory."

    author = "Bomi Lee"
    dateFormat = "2019/02/09"
    email = "bomi-lee-1@uiowa.edu"
    github_username = "bomibonnie"
    twitter_username = "bomiklee"  # leave empty quotes to omit
    gscholar_code = ""        # leave empty quotes to omit    

    page_color = "#f0f0f0"
    text_color = "#424242"
    link_color = "black"
    hover_color = "#fcd116"


    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
